isValidIpv4: 'Địa chỉ Ipv4'
isValidIpv6: 'Địa chỉ Ipv6'
isClass: 'Đ/c lớp: '
isPrivate: 'Đ/c private: '
isReserved: 'Đ/c nội bộ(reserved): '
invalidIp: 'Đ/c ip không phù hợp'
addBase: 'Đ/c cơ sở: '
addMask: 'Đ/c mask: '
addHostmask: 'Đ/c host mask: '
addBroadcast: 'Đ/c broadcast: '
size: 'Số host: '
first: 'Đ/c đầu: '
last: 'Đ/c cuối: '
shortForm: 'Rút gọn: '
hexForm: 'Dạng hex: '
binaryForm: 'Dạng nhị phân: '
ATM: 'Asynchronous Transfer Mode - kỹ thuật mạng định hướng kết nối'
ACK: 'Acknowledgement'
ARP: 'Address Resolution Protocol - Giao thức TCP/IP được sử dụng để liên kết động một địa chỉ IP cấp cao vào một địa chỉ phần cứng cấp thấp'
CGI: 'Common Gateway Interface - phương pháp cho phép giao tiếp giữa server và chương trình nhờ các định dạng đặc tả thông tin'
DNS: 'Domain Name System - hệ thống quản lý tên miền'
DOS: 'Denial of Service - Tấn công từ chối dịch vụ'
DES: 'Data Encrypt Standar - chuẫn mã hoá password thông dụng, rất khó bị crack, chỉ có một cách duy nhất và cũng là dễ nhất là dùng tự điển'
EGP: 'Exterior Gateway Protocol - giao thức nào được sử dụng bởi bộ định tuyến trong một hệ tự quản để thông báo khả năng đi đến mạng cho ho bộ định tuyến trong hệ tự quản khác'
FTP: 'File Transfer Protocol - giao thức truyền file trên mạng. Thường dùng để upload file lên Host, Server. Cổng mặc định là 21'
GUI: 'Graphic User Interface - giao diện đồ hoạ người sử dụng trong hệ điều hành Linux'
HTTP: 'Hyper-Text Transfer Protocol'
ICMP: 'Internet Control Message Protocol - giao thức xử lý các thông báo trạng thái cho IP'
IIS: 'Internet Information Server - chương trình WebServer nổi tiếng của Microsoft'
IPC: 'Inter-Process Communication - dùng trong chuyện sẻ chia dữ liệu giữa các ứng dụng và máy tính trên mạng (NT/2K)'
LAN: 'Local Area Network'
MAC: 'Media Access Control'
OS: 'Operation System'
OSI: 'Open System Interconnection'
OWA: 'Outlock Web Access - Module của Microsoft Exchanger Server (một Server phục vụ Mail), nó cho phép người dùng truy cập và quản trị Mailbox của họ từ xa thông qua Web Browser'
PPP: 'Point-to-Point - giao thức kết nối Internet tin cậy thông qua Modem'
POP3: 'Post Office Protocol Version 3 - check mail'
PKC: 'Public key cryptos - hệ thống mật (an ninh) mã sử dụng từ khóa chung'
RFC: 'Request For Comment - tập hợp những tài liệu về kiến nghị, đề xuất và những lời bình luận liên quan trực tiếp hoặc gián tiếp đến công nghệ, nghi thức mạng INTERNET'
SYN: 'The Synchronous Idle Character - ký tự đồng bộ hóa'
SGID: 'Set Group ID on execution'
SUID: 'Set User ID on execution'
SSI: 'Server Side Includes'
TCP: 'Transmission Control Protocol'
TCP/IP: 'Transmission Control Protocol and Internet Protocol'
UDP: 'User Datagram Protocol'
WWW: 'World Wide Web'
IPX/SPX: 'Internetwork Packet Exchange/Sequenced Packet Exchange'
NETBEUI: 'NetBIOS Extended User Interface'
iOSI: 'Thứ tự: Application, Presentation, Session, Transport, Network, Data Link, Physical'
iPRESENTATION: 'Mã hóa dữ liệu, Đơn vị Data. ASCII, EBCDIC, TIFF, GIF, PICT, JPEG'
iAPPLICATION: 'WWW, NFS, SNMP, Telnet, HTTP, FTP'
iTCP: 'Tầng Application'
iUDP: 'Tầng Application'
iLAN: 'Công nghệ phổ biến: Token Ring, FDDI, Ethernet'
iPROXY: 'Là máy đại diện cho một nhóm máy đi thực hiện một dịch vụ máy khách (client service) nào đó'
iSESSION: 'đồng bộ hoá quá trình liên lạc của hai máy và quản lý việc trao đổi dữ liệu. Lớp phiên này chịu trách nhiệm cho việc thiết lập, quản lý và chấm dứt session với máy từ xa. Session như NFS, NetBios names, RPC, SQL'
iTRANSPORT: 'lớp giao vận chịu trách nhiệm chuyển dữ liệu giữa các hệ thống đầu cuối hoặc máy chủ (host). SPX, TCP, UDP'
iNETWORK: 'là lớp có trách nhiệm quyết định xem dữ liệu sẽ đến máy nhận như thế nào. Lớp này nắm những thành phần như việc định địa chỉ, định tuyến, và các giao thức logic. Apple Talk DDP, IP, IPX'
iDATALINK: 'Đơn vị frame. Các gói dữ liệu được mã hóa và giải mã thành các bit. Nó cho biết giao thức truyền tải, quản lý và xử lý lỗi trong lớp vật lý Physical, điều khiển luồng và đồng bộ khung. PPP, FDDI, ATM, IEEE 802.5/ 802.2, IEEE 802.3/802.2, HDLC, Frame Relay'
LLC: 'Logical Link Control'
iLLC: 'điều khiển sự đồng bộ khung, điều khiển luồng và cung cấp một mức kiểm tra lỗi'
iPHYSICAL: 'truyền tải luồng bit, xung điện, tín hiệu radio hoặc ánh sáng thong qua mạng ở mức điện hoặc máy móc. Ethernet, FDDI, B8ZS, V.35, V.24, RJ45'
iSUBNETMASK: 'Nhằm tiết kiệm số lượng địa chỉ IP v4 hiện nay, đang bị hao dần vì số lượng người truy cập Internet ngày càng nhiều. Mặt khác tăng tính an toàn và tiết kiệm hơn cho người sử dụng internet, giới chuyên gia đã đưa ra biện pháp khắc phục là chia nhỏ địa chỉ IP.'